Fix underlinking with lld (missing -lm)
We need to explicitly search for and link with -lm if needed by
libc for math libraries like `log` and `sin`:
```
ld.lld: error: undefined reference due to --no-allow-shlib-undefined: sin
>>> referenced by ../.libs/libSDL_sound.so

ld.lld: error: undefined reference due to --no-allow-shlib-undefined: log
>>> referenced by ../.libs/libSDL_sound.so
```

It turns out Gentoo has actually had a patch for this since 2012 (mea
culpa!) but it never made its way upstream.

We're already using libtool, so just use the macro it provides for
this purpose.

Signed-off-by: Sam James <sam@gentoo.org>